version: 2.1

jobs:
  api:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:IWvA206TP1fzs7LxKB0Gnkf0a/At5p4Q6zNkuPx7EBc"
      - checkout
      - run: echo $SERVICE_ACCOUNT_KEY | base64 --decode > service-account-key.json && make verify
  tag:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:IWvA206TP1fzs7LxKB0Gnkf0a/At5p4Q6zNkuPx7EBc"
      - checkout
      - run: sh scripts/tag.sh
  publish:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:IWvA206TP1fzs7LxKB0Gnkf0a/At5p4Q6zNkuPx7EBc"
      - checkout
      - run: sh scripts/publish.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - api
      - tag:
          requires:
            - api
          filters:
            branches:
              only: master
      - publish:
          requires:
            - tag
          filters:
            branches:
              only: master
